name: pushbots_flutter
description: PushBots SDK, help you manage push notifications easily and effectivly.
version: 1.0.2
homepage: https://pushbots.com/
repository: https://github.com/pushbots/flutter-sdk

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"
  
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pushbots_flutter
        pluginClass: PushbotsFlutterPlugin
      ios:
        pluginClass: PushbotsFlutterPlugin